metadata:
  name: snake
  tier: frontend
image:
  name: snake
  repo: ghcr.io/ismaeladl
  ver: e42c5bbdd212bcab56d32f6b75384fe064d89158
  pullPol: IfNotPresent
spec:
  deploy:
    readySec: 5
    history: 10
    pod:
      priority: high
