metadata:
  name: snake
  tier: frontend
image:
  name: snake
  repo: ghcr.io/ismaeladl
  ver: bf6e605d3bf42cea23c3512f4888f4c22295d275
  pullPol: IfNotPresent
spec:
  deploy:
    readySec: 5
    history: 10
    pod:
      priority: high
