metadata:
  name: snake
  tier: frontend
image:
  name: snake
  repo: ghcr.io/ismaeladl
  ver: 04f2ff5a064982f4fb8b4310dbd19c0611d55673
  pullPol: IfNotPresent
spec:
  deploy:
    readySec: 5
    history: 10
    pod:
      priority: high
